//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_Pedidos_Web.PedidoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidoService.IPedidosService")]
    public interface IPedidosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Obtener", ReplyAction="http://tempuri.org/IPedidosService/ObtenerResponse")]
        Shared.DTOs.PedidosDTO[] Obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Obtener", ReplyAction="http://tempuri.org/IPedidosService/ObtenerResponse")]
        System.Threading.Tasks.Task<Shared.DTOs.PedidosDTO[]> ObtenerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/ObtenerPorId", ReplyAction="http://tempuri.org/IPedidosService/ObtenerPorIdResponse")]
        Shared.DTOs.PedidosDTO ObtenerPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/ObtenerPorId", ReplyAction="http://tempuri.org/IPedidosService/ObtenerPorIdResponse")]
        System.Threading.Tasks.Task<Shared.DTOs.PedidosDTO> ObtenerPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Agregar", ReplyAction="http://tempuri.org/IPedidosService/AgregarResponse")]
        void Agregar(Shared.DTOs.PedidosDTO pedidoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Agregar", ReplyAction="http://tempuri.org/IPedidosService/AgregarResponse")]
        System.Threading.Tasks.Task AgregarAsync(Shared.DTOs.PedidosDTO pedidoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Editar", ReplyAction="http://tempuri.org/IPedidosService/EditarResponse")]
        void Editar(Shared.DTOs.PedidosDTO pedidoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Editar", ReplyAction="http://tempuri.org/IPedidosService/EditarResponse")]
        System.Threading.Tasks.Task EditarAsync(Shared.DTOs.PedidosDTO pedidoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Eliminar", ReplyAction="http://tempuri.org/IPedidosService/EliminarResponse")]
        void Eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Eliminar", ReplyAction="http://tempuri.org/IPedidosService/EliminarResponse")]
        System.Threading.Tasks.Task EliminarAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Buscar", ReplyAction="http://tempuri.org/IPedidosService/BuscarResponse")]
        Shared.DTOs.PedidosDTO[] Buscar(string busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Buscar", ReplyAction="http://tempuri.org/IPedidosService/BuscarResponse")]
        System.Threading.Tasks.Task<Shared.DTOs.PedidosDTO[]> BuscarAsync(string busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Reporte", ReplyAction="http://tempuri.org/IPedidosService/ReporteResponse")]
        Shared.DTOs.PedidosDTO[] Reporte(System.DateTime fechaInicial, System.DateTime fechaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/Reporte", ReplyAction="http://tempuri.org/IPedidosService/ReporteResponse")]
        System.Threading.Tasks.Task<Shared.DTOs.PedidosDTO[]> ReporteAsync(System.DateTime fechaInicial, System.DateTime fechaFinal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidosServiceChannel : Gestor_Pedidos_Web.PedidoService.IPedidosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidosServiceClient : System.ServiceModel.ClientBase<Gestor_Pedidos_Web.PedidoService.IPedidosService>, Gestor_Pedidos_Web.PedidoService.IPedidosService {
        
        public PedidosServiceClient() {
        }
        
        public PedidosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Shared.DTOs.PedidosDTO[] Obtener() {
            return base.Channel.Obtener();
        }
        
        public System.Threading.Tasks.Task<Shared.DTOs.PedidosDTO[]> ObtenerAsync() {
            return base.Channel.ObtenerAsync();
        }
        
        public Shared.DTOs.PedidosDTO ObtenerPorId(int id) {
            return base.Channel.ObtenerPorId(id);
        }
        
        public System.Threading.Tasks.Task<Shared.DTOs.PedidosDTO> ObtenerPorIdAsync(int id) {
            return base.Channel.ObtenerPorIdAsync(id);
        }
        
        public void Agregar(Shared.DTOs.PedidosDTO pedidoDto) {
            base.Channel.Agregar(pedidoDto);
        }
        
        public System.Threading.Tasks.Task AgregarAsync(Shared.DTOs.PedidosDTO pedidoDto) {
            return base.Channel.AgregarAsync(pedidoDto);
        }
        
        public void Editar(Shared.DTOs.PedidosDTO pedidoDTO) {
            base.Channel.Editar(pedidoDTO);
        }
        
        public System.Threading.Tasks.Task EditarAsync(Shared.DTOs.PedidosDTO pedidoDTO) {
            return base.Channel.EditarAsync(pedidoDTO);
        }
        
        public void Eliminar(int id) {
            base.Channel.Eliminar(id);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(int id) {
            return base.Channel.EliminarAsync(id);
        }
        
        public Shared.DTOs.PedidosDTO[] Buscar(string busqueda) {
            return base.Channel.Buscar(busqueda);
        }
        
        public System.Threading.Tasks.Task<Shared.DTOs.PedidosDTO[]> BuscarAsync(string busqueda) {
            return base.Channel.BuscarAsync(busqueda);
        }
        
        public Shared.DTOs.PedidosDTO[] Reporte(System.DateTime fechaInicial, System.DateTime fechaFinal) {
            return base.Channel.Reporte(fechaInicial, fechaFinal);
        }
        
        public System.Threading.Tasks.Task<Shared.DTOs.PedidosDTO[]> ReporteAsync(System.DateTime fechaInicial, System.DateTime fechaFinal) {
            return base.Channel.ReporteAsync(fechaInicial, fechaFinal);
        }
    }
}
