//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestor_Pedidos_Web.ClienteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClienteService.IClientesService")]
    public interface IClientesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/Obtener", ReplyAction="http://tempuri.org/IClientesService/ObtenerResponse")]
        Shared.DTOs.ClientesDTO[] Obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/Obtener", ReplyAction="http://tempuri.org/IClientesService/ObtenerResponse")]
        System.Threading.Tasks.Task<Shared.DTOs.ClientesDTO[]> ObtenerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/ObtenerPorID", ReplyAction="http://tempuri.org/IClientesService/ObtenerPorIDResponse")]
        Shared.DTOs.ClientesDTO ObtenerPorID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/ObtenerPorID", ReplyAction="http://tempuri.org/IClientesService/ObtenerPorIDResponse")]
        System.Threading.Tasks.Task<Shared.DTOs.ClientesDTO> ObtenerPorIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/Agregar", ReplyAction="http://tempuri.org/IClientesService/AgregarResponse")]
        void Agregar(Shared.DTOs.ClientesDTO clienteDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/Agregar", ReplyAction="http://tempuri.org/IClientesService/AgregarResponse")]
        System.Threading.Tasks.Task AgregarAsync(Shared.DTOs.ClientesDTO clienteDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/Editar", ReplyAction="http://tempuri.org/IClientesService/EditarResponse")]
        void Editar(Shared.DTOs.ClientesDTO clienteDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/Editar", ReplyAction="http://tempuri.org/IClientesService/EditarResponse")]
        System.Threading.Tasks.Task EditarAsync(Shared.DTOs.ClientesDTO clienteDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/Buscar", ReplyAction="http://tempuri.org/IClientesService/BuscarResponse")]
        Shared.DTOs.ClientesDTO[] Buscar(string busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientesService/Buscar", ReplyAction="http://tempuri.org/IClientesService/BuscarResponse")]
        System.Threading.Tasks.Task<Shared.DTOs.ClientesDTO[]> BuscarAsync(string busqueda);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientesServiceChannel : Gestor_Pedidos_Web.ClienteService.IClientesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesServiceClient : System.ServiceModel.ClientBase<Gestor_Pedidos_Web.ClienteService.IClientesService>, Gestor_Pedidos_Web.ClienteService.IClientesService {
        
        public ClientesServiceClient() {
        }
        
        public ClientesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Shared.DTOs.ClientesDTO[] Obtener() {
            return base.Channel.Obtener();
        }
        
        public System.Threading.Tasks.Task<Shared.DTOs.ClientesDTO[]> ObtenerAsync() {
            return base.Channel.ObtenerAsync();
        }
        
        public Shared.DTOs.ClientesDTO ObtenerPorID(int id) {
            return base.Channel.ObtenerPorID(id);
        }
        
        public System.Threading.Tasks.Task<Shared.DTOs.ClientesDTO> ObtenerPorIDAsync(int id) {
            return base.Channel.ObtenerPorIDAsync(id);
        }
        
        public void Agregar(Shared.DTOs.ClientesDTO clienteDTO) {
            base.Channel.Agregar(clienteDTO);
        }
        
        public System.Threading.Tasks.Task AgregarAsync(Shared.DTOs.ClientesDTO clienteDTO) {
            return base.Channel.AgregarAsync(clienteDTO);
        }
        
        public void Editar(Shared.DTOs.ClientesDTO clienteDTO) {
            base.Channel.Editar(clienteDTO);
        }
        
        public System.Threading.Tasks.Task EditarAsync(Shared.DTOs.ClientesDTO clienteDTO) {
            return base.Channel.EditarAsync(clienteDTO);
        }
        
        public Shared.DTOs.ClientesDTO[] Buscar(string busqueda) {
            return base.Channel.Buscar(busqueda);
        }
        
        public System.Threading.Tasks.Task<Shared.DTOs.ClientesDTO[]> BuscarAsync(string busqueda) {
            return base.Channel.BuscarAsync(busqueda);
        }
    }
}
